### ISSUE TITLE
FYI, you left in your account details

### ISSUE THREAD

**Issue by AlexAndHisScripts** [cxan96/SwagbucksBot#2]
Might want to remove them :)

**Comment by LetsHaveFun** [comment]
Saw it as well, would create gitignore, currently talking to maintainer, thanks for bringing it up. 👍

**Comment by cxan96** [comment]
Thanks for letting me know guys, it's just a throwaway account but you're right it should be removed.

**Comment by LetsHaveFun** [comment]
Should be fixed in 3e20dab4ebb9e6c5f03d7cc5019e764f7235a643
